### ISSUE TITLE
Having issues using CLI

### ISSUE THREAD

**Issue by jaredvivints** [atlassian/gajira-cli#11]
I'm having issues with the below code. Result is further down. 
I've tried it with quotes, without quotes, as a flag. Missing something easy I know. 
Thanks

```
  
name: Jira Example

on: 
#   schedule:
#     - cron: "* 3 * * *"
  repository_dispatch:
  pull_request: 
    branches:
      - dev

jobs:
  deploy-bigquery:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Login to Jira
        id: login_jira
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Setup
        id: setup_jira_cli
        uses: atlassian/gajira-cli@v2.0.2
#       - name: help comment
#         run: jira help comment
      - name: Make comment on Jira issue
        run: jira -v comment comment='test cli comment add' ABCDE-1234
      - name: get issue info
        run: jira view --field=Summary ABCDE-1234

```

```
Run jira -v comment comment='test cli comment add' ABCDE-1234
  jira -v comment comment='test cli comment add' ABCDE-1234
  shell: /usr/bin/bash -e {0}
usage: jira comment [<flags>] [<ISSUE>]

Add comment to issue

Global flags:
      --help                   Show context-sensitive help (also try --help-long
                               and --help-man).
  -v, --verbose ...            Increase verbosity for debugging
  -e, --endpoint=ENDPOINT      Base URI to use for Jira
  -k, --insecure               Disable TLS certificate verification
  -Q, --quiet                  Suppress output to console
      --unixproxy=UNIXPROXY    Path for a unix-socket proxy
      --socksproxy=SOCKSPROXY  Address for a socks proxy
  -u, --user=USER              user name used within the Jira service
      --login=LOGIN            login name that corresponds to the user used for
                               authentication

Optional flags:
  -b, --browse             Open issue(s) in browser after operation
      --editor=EDITOR      Editor to use
  -t, --template=TEMPLATE  Template to use for output
      --noedit             Disable opening the editor
  -m, --comment=COMMENT    Comment message for issue

Args:
  [<ISSUE>]  issue id to update

ERROR Invalid Usage: unexpected ABCDE-1234
Error: Process completed with exit code 1.
```

another try
```
Run jira -v comment --noedit --comment='test cli comment add' ORION-3904
  jira -v comment --noedit --comment='test cli comment add' ORION-3904
  shell: /usr/bin/bash -e {0}
ERROR EOF
? Jira Password [***]:  25l
Error: Process completed with exit code 1.
```
