### ISSUE TITLE
Incorrect README snippet to refer to @v3 tag

### ISSUE THREAD

**Issue by maxlapides** [atlassian/gajira-cli#17]
Hi there! Thanks for updating this useful action!

The README has this code block:

```
- name: Setup
  uses: atlassian/gajira-cli@3.0.0
  with:
    version: 1.0.27
```

But, this won't work because `atlassian/gajira-cli@3.0.0` is not available. Neither is `atlassian/gajira-cli@3`. Right now, it seems only `atlassian/gajira-cli@master` will work. I've never published an action myself, but maybe these docs will help: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace
