### ISSUE TITLE
The examples provided do not work 🤔

### ISSUE THREAD

**Issue by adamjjeffery** [atlassian/gajira-cli#20]
The example provided [here](https://github.com/marketplace/actions/setup-jira) simply fails with the following error...

```
ERROR Invalid Usage: unknown long flag '--issue'
```

**Comment by Kruthika0** [comment]
Same for me. Also need some insights on using jira list. I am trying to list issues with a specific summary. But none of the specified options work

**Comment by adamjjeffery** [comment]
@Kruthika0 - Try this instead...

```
- name: Setup
   uses: atlassian/gajira-cli@v3
   with:
      version: 1.0.27

- name: Check ticket does not already exist
   id: find
   env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
   run: jira list --query "resolution=unresolved AND issuetype=Task AND summary~'${{ github.event.pull_request.title }}' AND project=ABC" --queryfields=issuetype,summary,priority,assignee,status,created,reporter,summary
```

It uses the `~` to see if the summary contains the given string.
